2022-10-18 08:53:50,880 : INFO : _log : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2022-10-18 08:53:50,880 : INFO : _log : [33mPress CTRL+C to quit[0m
2022-10-18 08:53:57,987 : INFO : home : –∑–∞–ø—Ä–æ—à–µ–Ω INDEX
2022-10-18 08:53:57,991 : INFO : _log : 127.0.0.1 - - [18/Oct/2022 08:53:57] "GET / HTTP/1.1" 200 -
2022-10-18 08:54:01,750 : INFO : all_candidates : –∑–∞–ø—Ä–æ—à–µ–Ω LIST
2022-10-18 08:54:01,752 : INFO : _log : 127.0.0.1 - - [18/Oct/2022 08:54:01] "GET /all/ HTTP/1.1" 200 -
2022-10-18 08:56:43,510 : WARNING : all_candidates : –ó–∞–ø–∏—Å—å –¥–ª—è –ª–æ–≥–≥–µ—Ä–∞ –æ–¥–∏–Ω
2022-10-18 08:56:49,104 : WARNING : all_candidates : –ó–∞–ø–∏—Å—å –¥–ª—è –ª–æ–≥–≥–µ—Ä–∞ –æ–¥–∏–Ω
2022-10-18 08:57:46,031 : WARNING : all_candidates : –ó–∞–ø–∏—Å—å –¥–ª—è –ª–æ–≥–≥–µ—Ä–∞ –æ–¥–∏–Ω
2022-10-18 09:07:59,850 : WARNING : all_candidates : –ó–∞–ø–∏—Å—å –¥–ª—è –ª–æ–≥–≥–µ—Ä–∞ –æ–¥–∏–Ω
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:main:Exception on /all/ [GET]
Traceback (most recent call last):
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\main.py", line 39, in all_candidates
    logging.ERROR("ERROR!!!")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:10:12] "[35m[1mGET /all/ HTTP/1.1[0m" 500 -
ERROR:main:Exception on /all/ [GET]
Traceback (most recent call last):
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\main.py", line 39, in all_candidates
    logging.ERROR("ERROR!!!")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:10:17] "[35m[1mGET /all/ HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:10:23] "GET / HTTP/1.1" 200 -
ERROR:main:Exception on /all/ [GET]
Traceback (most recent call last):
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\main.py", line 39, in all_candidates
    logging.ERROR("ERROR!!!")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:10:26] "[35m[1mGET /all/ HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:10:36] "GET /search/ HTTP/1.1" 200 -
ERROR:main:Exception on /all/ [GET]
Traceback (most recent call last):
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\CoreRYZ\PycharmProjects\0\HW11_HTML\main.py", line 39, in all_candidates
    logging.ERROR("ERROR!!!")
TypeError: 'int' object is not callable
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:10:40] "[35m[1mGET /all/ HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:11:12] "GET /all/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:11:23] "GET /search/ HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [18/Oct/2022 09:11:25] "GET / HTTP/1.1" 200 -
2022-10-18 09:24:05,617 : WARNING : all_candidates : –ó–∞–ø–∏—Å—å –¥–ª—è –ª–æ–≥–≥–µ—Ä–∞ –æ–¥–∏–Ω
2022-10-18 09:25:14,026 : WARNING : all_candidates : –ó–∞–ø–∏—Å—å –¥–ª—è –ª–æ–≥–≥–µ—Ä–∞ –æ–¥–∏–Ω
